server:
  port: 9999

serialport:
  name: COM5

tcp:
  server:
    port: 26

spring:

  application:
    name: iot-gateway

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8

logging:

  level:
    com.shaun: info
    com.ghgande.j2mod: info
  file: logs/${spring.application.name}.log

