server:
  port: 9999

serialport:
  name: COM5

tcp:
  server:
    port: 26
  contractclients:
  
    - ip: 10.252.31.144
      port: 26
      protocal: WaterQuality
      heartbeat:
        interval: 5
        echohex: 010300000002C40B
      frame: FixedLength
      frame-max-lengh: 1024
      fixed-length:
        decodeframelengh: 9
        encodeframelengh: 0
    
    - ip: 10.252.30.214
      port: 49153
      protocal: AirQuality
      frame: LengthField
      frame-max-lengh: 1024
      fixed-length:
        decodeframelengh: 9
        encodeframelengh: 0

    - ip: 10.252.31.145
      port: 0
      protocal: Modbus
      heartbeat:
        interval: 1
        echohex: 010300000002C40B

spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8

    
logging:
  level:
    com.shaun: info
    com.ghgande.j2mod: info
